imICR_prompt={
    "background": "The area of the computerized tomography that does not contain any of the other categories. It is typically the space surrounding the body or the parts of the body that are not of interest in the current analysis.",
    'adrenal_gland_left':'The left adrenal gland is a small, triangular organ located on top of the left kidney.', 
    'adrenal_gland_right':'The right adrenal gland is a small, triangular organ located on top of the right kidney.', 
    'aorta':' The main and largest artery in the human body, originating from the left ventricle of the heart and extending down to the abdomen, where it splits into two smaller arteries.',
    'autochthon_left':'The autochthon muscles on the left are deep muscles of the back', 
    'autochthon_right':'The autochthon muscles on the right are deep muscles of the back', 
    'brain':'The brain is located in the head.', 
    'clavicula_left':'The left clavicle is doubly curved long bone that forms part of the shoulder girdle, near the rib 1', 
    'clavicula_right':'The right clavicle is doubly curved long bone that forms part of the shoulder girdle, near the rib 1', 
    'colon':'The colon is located in the abdomen.', 
     'duodenum':'The duodenum is the first section of the small intestine, located near the stomach. ', 
     'esophagus':'The esophagus is a muscular tube connecting the throat to the stomach.  ', 
     'face':'The face is the front part of the head.', 
     'femur_left':'The left femur ( left thigh bone) is the longest and strongest bones in the body.', 
     'femur_right':'The right femur ( right thigh bone) is the longest and strongest bones in the body.', 
     'gallbladder':'The gallbladder is a pear-shaped sac behind the lower portion of the liver.', 
     'gluteus_maximus_left':'The left Gluteus Maximus is the largest muscle in the left buttock and adjacent to the gluteus medius and gluteus minimus muscles.', 
     'gluteus_maximus_right':'The right Gluteus Maximus is the largest muscle in the right buttock and adjacent to the gluteus medius and gluteus minimus muscles.', 
     'gluteus_medius_left':'The left Gluteus Medius is located near the outer surface of the pelvis and adjacent to the gluteus maximus and gluteus minimus.', 
     'gluteus_medius_right':'The right Gluteus Medius is located near the outer surface of the pelvis and adjacent to the gluteus maximus and gluteus minimus.', 
     'gluteus_minimus_left':'The left Gluteus Minimus is the smallest of the gluteal muscle, located beneath the gluteus medius.', 
     'gluteus_minimus_right':'The right Gluteus Minimus is the smallest of the gluteal muscle, located beneath the gluteus medius.', 
     'heart_atrium_left':'The left heart atrium is a upper chamber of the heart.', 
     'heart_atrium_right':'The right heart atrium is a upper chamber of the heart.', 
     'heart_myocardium':'Myocardium is the muscular wall of the heart.', 
     'heart_ventricle_left':'The left heart ventricle is a lower chamber of the heart.', 
     'heart_ventricle_right':'The right heart ventricle is a lower chamber of the heart.', 
     'hip_left':'The left hip connect the left thigh bone (femur) to the pelvis.', 
     'hip_right':'The left hip connect the right thigh bone (femur) to the pelvis.', 
     'humerus_left':'The left humerus is the long bone in the upper left arm from the shoulder to the elbow, connecting the scapula and the lower arm bones.', 
     'humerus_right':'The right humerus is the long bone in the upper right arm from the shoulder to the elbow, connecting the scapula and the lower arm bones.', 
     'iliac_artery_left':'The left iliac artery is a major blood vessel in the pelvic region that supplies blood to the left lower limb.', 
     'iliac_artery_right':'The right iliac artery is a major blood vessel in the pelvic region that supplies blood to the right lower limb.', 
     'iliac_vena_left':'The left iliac vein a large blood vessel connecting from the left lower limb back to the heart', 
     'iliac_vena_right':'The right iliac vein a large blood vessel connecting from the right lower limb back to the heart', 
     'iliopsoas_left':'The left iliopsoas is a large muscle in the left lower body near the spinal column.', 
     'iliopsoas_right':'The right iliopsoas is a large muscle in the right lower body near the spinal column.', 
     'inferior_vena_cava':'The inferior vena cava is the largest vein in the body from the lower half of the body back to the heart.', 
     'kidney_left':'The left kidney is located slightly higher than the right kidney due to the position of the liver.', 
     'kidney_right':'The right kidney is located slightly lower than the left kidney due to the position of the liver.', 
     'liver':'The liver is the largest internal organ, located in the upper right part of the abdomen, beneath the diaphragm and on top of the stomach, right kidney and intestines. ', 
     'lung_lower_lobe_left':'The left lower lung lobe is the bottom section of the left lung.', 
     'lung_lower_lobe_right':'The right lower lung lobe is the largest section of the right lung.', 
     'lung_middle_lobe_right':'The right middel lung lobe is a small lobe of the right lung.',
     'lung_upper_lobe_left':'The left upper lung lobe is the top section of the left lung.', 
     'lung_upper_lobe_right':'The right upper lung lobe is a small lobe of the right lung.', 
     'pancreas':'The pancrease is an organ located in the abdomen, behind the stomach.',
     'portal_vein_and_splenic_vein':'The portal vein and splenic vein is from the gastrointestinal tract and spleen to liver.',
     'pulmonary_artery':'The pulmonary artery is from the right ventricle of the heart to the lungs.', 
     'rib_left_1':'The left first rib located near the left clavicle, from the first thoracic vertebrae.',
     'rib_left_10':'The left tenth rib, from the tenth thoracic vertebrae.', 
     'rib_left_11':'The left eleventh rib, from the eleventh thoracic vertebrae.',
     'rib_left_12':'The left twelfth rib is the lowest rib, from the twelfth thoracic vertebrae. ', 
     'rib_left_2':'The left second rib, from the second thoracic vertebrae.', 
     'rib_left_3':'The left third rib, from the third thoracic vertebrae.', 
     'rib_left_4':'The left fourth rib, from the fourth thoracic vertebrae.', 
     'rib_left_5':'The left fifth rib, from the fifth thoracic vertebrae.', 
     'rib_left_6':'The left sixth rib, from the sixth thoracic vertebrae.', 
     'rib_left_7':'The left seventh rib, from the seventh thoracic vertebrae.', 
     'rib_left_8':'The left eighth rib, from the eighth thoracic vertebrae.', 
     'rib_left_9':'The left ninth rib, from the ninth thoracic vertebrae.', 
     'rib_right_1':'The right first rib located near the right clavicle, from the first thoracic vertebrae.', 
     'rib_right_10':'The right tenth rib, from the tenth thoracic vertebrae.',
     'rib_right_11':'The right eleventh rib, from the eleventh thoracic vertebrae.', 
     'rib_right_12':'The right twelfth rib is the lowest rib, from the twelfth thoracic vertebrae.', 
     'rib_right_2':'The right second rib, from the second thoracic vertebrae.', 
     'rib_right_3':'The right third rib, from the third thoracic vertebrae.', 
     'rib_right_4':'The right fourth rib, from the fourth thoracic vertebrae.', 
     'rib_right_5':'The right fifth rib, from the fifth thoracic vertebrae.', 
     'rib_right_6':'The right sixth rib, from the sixth thoracic vertebrae.', 
     'rib_right_7':'The right seventh rib, from the seventh thoracic vertebrae.', 
     'rib_right_8':'The right eighth rib,from the eighth thoracic vertebrae.', 
     'rib_right_9':'The right ninth rib, from the ninth thoracic vertebrae.', 
     'sacrum':'The sacrum is a large, triangular bone at the base of the spine.', 
     'scapula_left':'The left scapula (shoulder blade), is a flat, triangular bone located on the upper left side of the back, connecting the left humerus and the left clavicle.', 
     'scapula_right':'The right scapula (shoulder blade), is a flat, triangular bone located on the upper right side of the back, connecting the right humerus and the right clavicle.', 
     'small_bowel':'The small bowel is a long, coiled organ in the digestive system, located between the stomach and the large intestine. ', 
     'spleen':'The spleen is an organ located in the upper left part of the abdomen, under the rib cage.', 
     'stomach':'The stomach, a pouch-like organ located in the upper part of the abdominal cavity, connects the esophagus with the small intestine, which is a muscular organ located on the left size of the upper abdomen, near with liver, spleen and pancreas.', 
     'trachea':'The trachea is a tube connect to lungs.', 
     'urinary_bladder':'The urinary bladder is a hollow muscular organ, located in the lower abdomen and connect to kidneys.', 
     'vertebrae_C1':'The first cervical vertebra.', 
     'vertebrae_C2':'The second cervical vertebra.', 
     'vertebrae_C3':'The third cervical vertebra.', 
     'vertebrae_C4':'The fourth cervical vertebra.', 
     'vertebrae_C5':'The fifth cervical vertebra.', 
     'vertebrae_C6':'The sixth cervical vertebra.',
     'vertebrae_C7':'The seventh cervical vertebra.', 
     'vertebrae_L1':'The first lumbar vertebra.', 
     'vertebrae_L2':'The second lumbar vertebra.', 
     'vertebrae_L3':'The third lumbar vertebra.', 
     'vertebrae_L4':'The fouth lumbar vertebra.', 
     'vertebrae_L5':'The fifth lumbar vertebra.', 
     'vertebrae_T1':'The first thoracic vertebra, near the left first rib and right first rib.', 
     'vertebrae_T10':'The tenth thoracic vertebra, near the left tenth rib and right tenth rib.', 
     'vertebrae_T11':'The eleventh thoracic vertebra, near the left eleventh rib and right eleventh rib.', 
     'vertebrae_T12':'The twelfth thoracic vertebra, near the left twelfth rib and right twelfth rib.', 
     'vertebrae_T2':'The second thoracic vertebra, near the left second rib and right second rib.', 
     'vertebrae_T3':'The third thoracic vertebra, near the left third rib and right third rib.', 
     'vertebrae_T4':'The fourth thoracic vertebra, near the left fourth rib and right fourth rib.', 
     'vertebrae_T5':'The fifth thoracic vertebra, near the left fifth rib and right fifth rib.', 
     'vertebrae_T6':'The sixth thoracic vertebra, near the left sixth rib and right sixth rib.', 
     'vertebrae_T7':'The seventh thoracic vertebra, near the left seventh rib and right seventh rib.', 
     'vertebrae_T8':'The eighth thoracic vertebra, near the left eighth rib and right eighth rib.', 
     'vertebrae_T9':'The ninth thoracic vertebra, near the left ninth rib and right ninth rib.',

     'adrenal_glands':'Adrenal Glands are a pair of triangular organs located on top of each kidney.',
     'autochthon muscles':'Autochthon Muscles are the deep muscles of the back',
     'clavicles':'Clavicles connect the upper limbs to the trunk.',
     'femurs':'Femurs (thigh bones) are the longest and strongest bones in the body.',
     'gluteus muscles':'Gluteus muscles are the muscles of the buttocks.',
     'hips':'The hip joints are near with the femurs and pelvic bones.',
     'humerus':'The humerus are the upper arm bone.',
     'iliac arteries':'The iliac arteries are the major arteries in the pelvis.',
     'iliac veins':'The iliac veins are the major veins in the pelvis.',
     'iliopsoas muscles':'The iliopsoas muscles are the deep hip flexor muscles.',
     'kidneys':'The kidnes are the bean-shaped organs, located in the lower back.',
     'lungs':'The lungs are the primary organs in the thoracic.',
     'scapulas':'The scapulas connect the clavicle and humerus in the arms.',
     'vertebrae_C':'The cervical vertebrae located in the neck region',
     'vertebrae_T':'The thoracic vertebrae located in the chest region',
     'vertebrae_L':'The lumbar vertebrae located in the lower back',
     'heart':'The central organ of the cardiovascular system, located in the thoracic cavity.',

     'brain and face':'The brain and face are near head, at the top of the body.',
     'vessels':'The vessles are the network of blood vessels (arteries, veins, capillaries)',
     'abdominal organs':'Organs located in the abdominal cavity',
     'thoracic organs':'Organs located in the thoracic cavity',
     'organs':'all organs in the body',
     'vertebraes':'The entire vertebral column',
     'muscles':'all muscles in the body, interact with bones and vessels',
     'ribs':'All ribs in the body, interact with the thoracic vertebrae and muscles.',
     'bones':'The skeletal framework of the body, interact with all body tissues.',

     'cardiovascular system':'cardiovascular system is responsible for circulating blood throughout the body.',
     'gastrointestinal tract':'gastrointestinal tract is responsible for digestion and absorption of nutrients.',
     'respiratory system':'Respiratory system is responsible for gas exchange.',
     'urinary system':'urinary system is responsible for excretion of waste products',
     'digestive system':'digestive system is responsible for breaking down food, absorbing nutrients and removing waste.',
     'musculoskeletal system':'musculoskeletal system contain muscles and bones, responsible for body movement, support and protection.',
}

